import crypto from "node:crypto";

// --- OstrichID ---
//
// A random secret the user needs (with username and password) to log in.
// Clients generate it and derive the account's keys from it (see
// frontend/src/lib/crypto.ts); it never reaches the server. Accounts
// created before end-to-end encryption had it generated by the server,
// which kept its hash (ostrich_id_hash): those are upgraded once with the
// raw ID, see /api/auth/keys/upgrade.

// No 0/O, 1/I/L: easy to copy by hand. 31 symbols ^ 20 ≈ 99 bits.
const OSTRICH_ID_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";
const OSTRICH_ID_LENGTH = 20;

// Accepts the ID as typed: any case, with or without dashes and spaces.
export const OSTRICH_ID_INPUT_PATTERN = "^[A-Za-z0-9 -]{0,40}$";

// The canonical form of a typed ID, or null if it cannot be valid.
export function normalizeOstrichId(input: string): string | null {
  const id = input.replace(/[\s-]/g, "").toUpperCase();

  if (id.length !== OSTRICH_ID_LENGTH) {
    return null;
  }

  for (const char of id) {
    if (!OSTRICH_ID_ALPHABET.includes(char)) {
      return null;
    }
  }

  return id;
}

// The ID is a long random value, so a fast hash is enough (like session
// tokens): it cannot be guessed from the hash.
export function hashOstrichId(id: string): string {
  return crypto.createHash("sha256").update(id).digest("hex");
}

export function ostrichIdMatches(input: string, hash: string): boolean {
  const id = normalizeOstrichId(input);

  if (!id) {
    return false;
  }

  return crypto.timingSafeEqual(
    Buffer.from(hashOstrichId(id), "hex"),
    Buffer.from(hash, "hex"),
  );
}

// --- end-to-end encryption keys ---

// hex(32 bytes) derived from the OstrichID on the client; see
// frontend/src/lib/crypto.ts for the scheme.
export const AUTH_KEY_PATTERN = "^[0-9a-f]{64}$";

export const keyMaterialSchema = {
  type: "object",
  required: ["auth_key", "public_key", "encrypted_private_key"],
  properties: {
    auth_key: { type: "string", pattern: AUTH_KEY_PATTERN },
    // base64 of a 32-byte X25519 public key.
    public_key: { type: "string", pattern: "^[A-Za-z0-9+/]{43}=$" },
    // base64 of nonce (24) + encrypted private key (32) + tag (16).
    encrypted_private_key: { type: "string", pattern: "^[A-Za-z0-9+/]{96}$" },
  },
} as const;

export type KeyMaterial = {
  auth_key: string;
  public_key: string;
  encrypted_private_key: string;
};

export function hashAuthKey(authKey: string): string {
  return crypto.createHash("sha256").update(authKey).digest("hex");
}

export function authKeyMatches(authKey: string | undefined, hash: string) {
  if (!authKey || !/^[0-9a-f]{64}$/.test(authKey)) {
    return false;
  }

  return crypto.timingSafeEqual(
    Buffer.from(hashAuthKey(authKey), "hex"),
    Buffer.from(hash, "hex"),
  );
}

// --- usernames ---

// Letters, digits, "_", "." and "-" only: usernames are shown in terminals,
// so control characters and look-alike whitespace are not allowed.
export const usernameSchema = {
  type: "string",
  minLength: 3,
  maxLength: 32,
  pattern: "^[A-Za-z0-9_.-]+$",
} as const;

export const passwordSchema = {
  type: "string",
  minLength: 8,
  maxLength: 128,
} as const;

// The username can be changed right after registration, then once per
// USERNAME_CHANGE_INTERVAL_DAYS.
export const USERNAME_CHANGE_INTERVAL_DAYS = 28;

const DAY_MS = 24 * 60 * 60 * 1000;

export function nextUsernameChangeAt(changedAt: Date | null): Date | null {
  if (!changedAt) {
    return null;
  }

  const next = new Date(
    changedAt.getTime() + USERNAME_CHANGE_INTERVAL_DAYS * DAY_MS,
  );

  return next > new Date() ? next : null;
}

// SQL for the user's current avatar id (null without one), for queries
// that select from "users".
export const AVATAR_ID_COLUMN = `(
  SELECT avatars.id FROM avatars WHERE avatars.user_id = users.id
) AS avatar_id`;

// Profile fields shown next to a user's name everywhere: avatar and the
// developer badge. For queries that select from "users".
export const PROFILE_COLUMNS = `${AVATAR_ID_COLUMN}, users.is_developer`;

// The user as the API returns it to its owner.
export function accountView(row: {
  id: string;
  username: string;
  created_at: Date;
  username_changed_at: Date | null;
  avatar_id?: string | null;
  is_developer?: boolean;
  show_presence?: boolean;
  read_receipts?: boolean;
}) {
  return {
    id: row.id,
    username: row.username,
    created_at: row.created_at,
    // null when the username can be changed now.
    next_username_change_at: nextUsernameChangeAt(row.username_changed_at),
    avatar_id: row.avatar_id ?? null,
    is_developer: row.is_developer ?? false,
    // Privacy settings.
    show_presence: row.show_presence ?? true,
    read_receipts: row.read_receipts ?? true,
  };
}
