import crypto from "node:crypto";

// --- OstrichID ---
//
// A random second secret, generated by the server when the account is
// created and needed (with the username and password) to log in. It is
// shown to the user once; only its hash is stored, so it cannot be shown
// again or recovered.

// No 0/O, 1/I/L: easy to copy by hand. 31 symbols ^ 20 ≈ 99 bits.
const OSTRICH_ID_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";
const OSTRICH_ID_LENGTH = 20;
const OSTRICH_ID_GROUP = 4;

// Accepts the ID as typed: any case, with or without dashes and spaces.
export const OSTRICH_ID_INPUT_PATTERN = "^[A-Za-z0-9 -]{0,40}$";

export function generateOstrichId(): string {
  let id = "";

  for (let i = 0; i < OSTRICH_ID_LENGTH; i++) {
    id += OSTRICH_ID_ALPHABET[crypto.randomInt(OSTRICH_ID_ALPHABET.length)];
  }

  return id;
}

// "K7QM-3XRA-9TPW-H2DC-M8VN"
export function formatOstrichId(id: string): string {
  return id.match(new RegExp(`.{1,${OSTRICH_ID_GROUP}}`, "g"))!.join("-");
}

// The canonical form of a typed ID, or null if it cannot be valid.
export function normalizeOstrichId(input: string): string | null {
  const id = input.replace(/[\s-]/g, "").toUpperCase();

  if (id.length !== OSTRICH_ID_LENGTH) {
    return null;
  }

  for (const char of id) {
    if (!OSTRICH_ID_ALPHABET.includes(char)) {
      return null;
    }
  }

  return id;
}

// The ID is a long random value, so a fast hash is enough (like session
// tokens): it cannot be guessed from the hash.
export function hashOstrichId(id: string): string {
  return crypto.createHash("sha256").update(id).digest("hex");
}

export function ostrichIdMatches(input: string, hash: string): boolean {
  const id = normalizeOstrichId(input);

  if (!id) {
    return false;
  }

  return crypto.timingSafeEqual(
    Buffer.from(hashOstrichId(id), "hex"),
    Buffer.from(hash, "hex"),
  );
}

// --- usernames ---

// Letters, digits, "_", "." and "-" only: usernames are shown in terminals,
// so control characters and look-alike whitespace are not allowed.
export const usernameSchema = {
  type: "string",
  minLength: 3,
  maxLength: 32,
  pattern: "^[A-Za-z0-9_.-]+$",
} as const;

export const passwordSchema = {
  type: "string",
  minLength: 8,
  maxLength: 128,
} as const;

// The username can be changed right after registration, then once per
// USERNAME_CHANGE_INTERVAL_DAYS.
export const USERNAME_CHANGE_INTERVAL_DAYS = 28;

const DAY_MS = 24 * 60 * 60 * 1000;

export function nextUsernameChangeAt(changedAt: Date | null): Date | null {
  if (!changedAt) {
    return null;
  }

  const next = new Date(
    changedAt.getTime() + USERNAME_CHANGE_INTERVAL_DAYS * DAY_MS,
  );

  return next > new Date() ? next : null;
}

// SQL for the user's current avatar id (null without one), for queries
// that select from "users".
export const AVATAR_ID_COLUMN = `(
  SELECT avatars.id FROM avatars WHERE avatars.user_id = users.id
) AS avatar_id`;

// The user as the API returns it to its owner.
export function accountView(row: {
  id: string;
  username: string;
  created_at: Date;
  username_changed_at: Date | null;
  avatar_id?: string | null;
}) {
  return {
    id: row.id,
    username: row.username,
    created_at: row.created_at,
    // null when the username can be changed now.
    next_username_change_at: nextUsernameChangeAt(row.username_changed_at),
    avatar_id: row.avatar_id ?? null,
  };
}
